src/Volo.Abp.Image.Web/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Volo.Abp.Imaging;

namespace Volo.Abp.Image.Web.Pages;

public class IndexModel : ImagePageModel
{
    [BindProperty]
    public IFormFile File { get; set; }

    private readonly IEnumerable<IImageResizerContributor> _imageResizerContributors;
    
    protected readonly IEnumerable<IImageCompressorContributor> ImageCompressorContributors;

    public IndexModel(IImageResizer imageResizer, IEnumerable<IImageResizerContributor> imageResizerContributors, IEnumerable<IImageCompressorContributor> imageCompressorContributors)
    {
        _imageResizerContributors = imageResizerContributors;
        ImageCompressorContributors = imageCompressorContributors;
    }

    public void OnGet()
    {
        
    }
    
    public async Task<IActionResult> OnPostResize()
    {
        var rnd = new Random();
        Dictionary<string,List<(string contributor, string data)>> results = new();

        for (var i = 0; i < 25; i++)
        {
            var args = new ImageResizeArgs(rnd.Next(100, 1000), rnd.Next(100, 1000), (ImageResizeMode)rnd.Next(0, 7));
        
            foreach (var contributor in _imageResizerContributors)
            {
                var result = await contributor.TryResizeAsync(File.OpenReadStream(), args);
                if (result.State != ProcessState.Done)
                {
                    continue;
                }

                var key = $"{args.Width}x{args.Height}x{args.Mode}";
                var newValue = (contributor.GetType().Name, Convert.ToBase64String(await result.Result.GetAllBytesAsync()));
                if(results.TryGetValue(key, out var value))
                {
                    value.Add(newValue);
                }
                else
                {
                    results.TryAdd(key ,new List<(string contributor, string data)> {newValue});
                }
            }
        }

        return PartialView("/Pages/Test.cshtml", results);
    }
    
    public async Task<IActionResult> OnPostCompress()
    {
        Dictionary<string,List<(string contributor, string data)>> results = new();

        foreach (var contributor in ImageCompressorContributors)
        {
            var result = await contributor.TryCompressAsync(File.OpenReadStream(), File.ContentType);
            if (result.State != ProcessState.Done)
            {
                continue;
            }

            var key = $"{File.FileName}";
            var newValue = (contributor.GetType().Name, Convert.ToBase64String(await result.Result.GetAllBytesAsync()));
            if(results.TryGetValue(key, out var value))
            {
                value.Add(newValue);
            }
            else
            {
                results.TryAdd(key ,new List<(string contributor, string data)> {newValue});
            }
        }
        
        return PartialView("/Pages/Test.cshtml", results);
    }
}

src/Volo.Abp.Image.Web/Pages/Index.cshtml
@page
@using Microsoft.AspNetCore.Mvc.Localization
@using Volo.Abp.Image.Localization
@using Volo.Abp.Users
@model Volo.Abp.Image.Web.Pages.IndexModel
@inject IHtmlLocalizer<ImageResource> L
@inject ICurrentUser CurrentUser

@section styles {
    <abp-style src="/Pages/Index.css"/>
}

@section scripts {
    <abp-script src="/Pages/Index.js"/>
}

<div class="container">
    <h1>Resize</h1>
    <form enctype="multipart/form-data" asp-page-handler="Resize">
        <abp-input asp-for="File"></abp-input>
        <abp-button type="submit" button-type="Primary" accept="image/*">Resize</abp-button>
    </form>

    <br/>
    <br/>
    <br/>

    <h1>Compress</h1>
    <form enctype="multipart/form-data" asp-page-handler="Compress">
        <abp-input asp-for="File" accept="image/*"></abp-input>
        <abp-button type="submit" button-type="Primary">Compress</abp-button>
    </form>
</div>

src/Volo.Abp.Image.Web/Pages/Test.cshtml
@using Volo.Abp.AspNetCore.Mvc.UI.Theming
@model Dictionary<string, List<(string contributor, string data)>>
@inject Volo.Abp.AspNetCore.Mvc.UI.Theming.ITheme Theme

@{
    Layout = Theme.GetEmptyLayout();
    var index = 0;
}
@foreach (var i in Model)
{
    <h3>Image @(++index) @i.Key</h3>

    <abp-row>
        @foreach (var valueTuple in i.Value)
        {
            <abp-column size="_6">

                <h4>@valueTuple.contributor</h4>
                <img src="data:image/gif;base64,@valueTuple.data" alt="@valueTuple.contributor"/>

            </abp-column>
        }
    </abp-row>


    <hr/>
}

<script>
var container = document.querySelector('.container');
container.style.maxWidth = '100%';
</script>